### ISSUE TITLE
Add solution for median of two solutions

### ISSUE THREAD

**Issue by Blakeinstein** [GDSCNITD/DSA101#8]
https://gdscnitd.github.io/DSA101/problems/arrays/Median-of-2-sorted-arrays

Update the respective page to include a solution. Additionally if possible, convert the file to .mdx and add a tabbed solutions for multiple languages.

Refer to https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks to know how.

**Comment by VigneshRamanathan101** [comment]
@Blakeinstein is this issue still open?

**Comment by Blakeinstein** [comment]
Hi! I graduated and am not upto date but if its marked open then it probably still is. Feel free to make a PR if that's what you were looking for and I can review and merge it 😀

**Comment by VigneshRamanathan101** [comment]
@Blakeinstein can you assign it to me?

**Comment by VigneshRamanathan101** [comment]
@Blakeinstein  I have created a PR for this issue can you approve it?

**Comment by VigneshRamanathan101** [comment]
@Blakeinstein Can we close this issue?
